name: kafka-connect-spooldir
lang: java
lang_version: 8
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp
  extra_deploy_args: -Dcloud -Pjenkins
  extra_build_args: -Dcloud -Pjenkins
  generate_connect_changelogs: true
  trivy_scan: true
  run_pint_merge: true
code_artifact:
  enable: true
  package_paths:
    - maven-snapshots/maven/com.github.jcustenborder.kafka.connect/kafka-connect-spooldir
